/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas301;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblOperando1 = new javax.swing.JLabel();
        lblOperando2 = new javax.swing.JLabel();
        txtOperando1 = new javax.swing.JTextField();
        txtOperando2 = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnSUB = new javax.swing.JButton();
        btnDIV = new javax.swing.JButton();
        btnMUL = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblResultadoCalculado = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Calculadora");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Aplicação Gráfica 301");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblOperando1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOperando1.setText("Operando 1:");

        lblOperando2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOperando2.setText("Operando 2:");

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnSUB.setText("SUB");
        btnSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUBActionPerformed(evt);
            }
        });

        btnDIV.setText("DIV");
        btnDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVActionPerformed(evt);
            }
        });

        btnMUL.setText("Mul");
        btnMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMULActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultado.setText("Resultado");

        lblResultadoCalculado.setText(".............");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperando1)
                    .addComponent(lblOperando2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtOperando1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                .addComponent(txtOperando2))
                            .addComponent(lblResultado)
                            .addComponent(btnLimpar)
                            .addComponent(lblResultadoCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMUL)
                            .addComponent(btnDIV)
                            .addComponent(btnSUB)
                            .addComponent(btnADD))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblOperando1)
                                    .addComponent(txtOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnADD)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOperando2)
                            .addComponent(txtOperando2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(btnSUB))
                    .addComponent(lblResultado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDIV)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultadoCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnMUL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(515, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        try {
            String strOper1 = txtOperando1.getText();
            String strOper2 = txtOperando2.getText();
            int num1 = Integer.parseInt(strOper1);
            int num2 = Integer.parseInt(strOper2);
            int soma = num1 + num2;
            String strSoma = String.valueOf(soma);
            lblResultadoCalculado.setText(strSoma);            
        }catch (NumberFormatException e){
              // System.out.println("erro= "+e.toString());
              // System.out.println("Entrada INVÁLIDA - Digite Corretamente");
            JOptionPane.showMessageDialog(null, "Entrada INVÁLIDA - Digite Corretamente");
        }
        
        

    }//GEN-LAST:event_btnADDActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtOperando1.setText("");
        txtOperando2.setText("");
        lblResultadoCalculado.setText("................");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUBActionPerformed
        // TODO add your handling code here:
        try {
        String strOper1 = txtOperando1.getText();
        String strOper2 = txtOperando2.getText();
        int num1 = Integer.parseInt(strOper1);
        int num2 = Integer.parseInt(strOper2);
        int sub = num1 - num2;
        String strSub = String.valueOf(sub);
        lblResultadoCalculado.setText(strSub);                        
        }catch (NumberFormatException e){
              // System.out.println("erro= "+e.toString());
              // System.out.println("Entrada INVÁLIDA - Digite Corretamente");
            JOptionPane.showMessageDialog(null, "Entrada INVÁLIDA - Digite Corretamente");
        }    

    }//GEN-LAST:event_btnSUBActionPerformed

    private void btnDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVActionPerformed
        // TODO add your handling code here:
        try {
            String strOper1 = txtOperando1.getText();
            String strOper2 = txtOperando2.getText();
            int num1 = Integer.parseInt(strOper1);
            int num2 = Integer.parseInt(strOper2);
            int divi = num1 / num2;
            String strDiv = String.valueOf(divi);
            lblResultadoCalculado.setText(strDiv);            
        }catch (NumberFormatException e){
              // System.out.println("erro= "+e.toString());
              // System.out.println("Entrada INVÁLIDA - Digite Corretamente");
            JOptionPane.showMessageDialog(null, "Entrada INVÁLIDA - Digite Corretamente");
        }
    }//GEN-LAST:event_btnDIVActionPerformed

    private void btnMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMULActionPerformed
        // TODO add your handling code here:
        try {
            String strOper1 = txtOperando1.getText();
            String strOper2 = txtOperando2.getText();
            int num1 = Integer.parseInt(strOper1);
            int num2 = Integer.parseInt(strOper2);
            int multi = num1 * num2;
            String strMulti = String.valueOf(multi);
            lblResultadoCalculado.setText(strMulti);
        }catch (NumberFormatException e){
              // System.out.println("erro= "+e.toString());
              // System.out.println("Entrada INVÁLIDA - Digite Corretamente");
            JOptionPane.showMessageDialog(null, "Entrada INVÁLIDA - Digite Corretamente");
        }    
    

    }//GEN-LAST:event_btnMULActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDIV;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMUL;
    private javax.swing.JButton btnSUB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOperando1;
    private javax.swing.JLabel lblOperando2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultadoCalculado;
    private javax.swing.JTextField txtOperando1;
    private javax.swing.JTextField txtOperando2;
    // End of variables declaration//GEN-END:variables
}
