/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas301;

import java.sql.*;
import Acesso301DAO.ModuloConexao;
import java.awt.Color;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class TelaSearchLicenca extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void consultarLic() {

        // 1 Criar a String com o comando SQL.
        //String txtSearch = textLicSearch.getText();
        String txtSearch = textLicSearch.getText();
        String sql = "select cdliccont,dsnomeresp,dscontrato from tblicencont where cdliccont =" + txtSearch;
        try {
            if (textLicSearch.getText() != "") {
                // Finalizar a preparação do comando na conexao do banco.
                pst = conexao.prepareStatement(sql);
                // Executar o comando/Consulta.
                rs = pst.executeQuery();
                // Verificar/testar o resultado da Consulta
                if (rs.next()) {

                    ResultSet resultado = pst.executeQuery(sql);

                    DefaultTableModel model = (DefaultTableModel) tblsearchLic.getModel();
                    model.setNumRows(0);

                    while (resultado.next()) {
                        model.addRow(new Object[]{
                            //retorna os dados da tabela do BD, cada campo e um coluna.
                            resultado.getString("cdliccont"),
                            resultado.getString("dsnomeresp"),
                            resultado.getString("dscontrato")
                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cadastro inexistente - Verifique.");
                    textLicSearch.setText("");
                    DefaultTableModel model = (DefaultTableModel) tblsearchLic.getModel();
                    model.setNumRows(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Banco de Dados com ERRO!!!");
            System.out.println(e);
        }

    }

    public void consultarTodas() {

        // 1 Criar a String com o comando SQL.
        String sql = "Select cdliccont,dsnomeresp,dscontrato from tblicencont;";
        try {
            // Finalizar a preparação do comando na conexao do banco.
            pst = conexao.prepareStatement(sql);
            // Executar o comando/Consulta.
            rs = pst.executeQuery();
            // Verificar/testar o resultado da Consulta
            if (rs.next()) {

                ResultSet resultado = pst.executeQuery(sql);

                DefaultTableModel model = (DefaultTableModel) tblsearchLic.getModel();
                model.setNumRows(0);

                while (resultado.next()) {
                    model.addRow(new Object[]{
                        //retorna os dados da tabela do BD, cada campo e um coluna.
                        resultado.getString("cdliccont"),
                        resultado.getString("dsnomeresp"),
                        resultado.getString("dscontrato")
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Banco de Dados com ERRO!!!");
            System.out.println(e);
        }

    }

    public TelaSearchLicenca() {
        initComponents();
        conexao = ModuloConexao.connector();
        consultarTodas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textLicSearch = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsearchLic = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Licença Contratada");
        setResizable(false);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Descrição da Licença:");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones301/Search2-icon.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tblsearchLic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Lic", "Nome Responsavel", "Descrição"
            }
        ));
        tblsearchLic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsearchLicMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsearchLic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textLicSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textLicSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(411, 214));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultarLic();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tblsearchLicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsearchLicMouseClicked

    }//GEN-LAST:event_tblsearchLicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSearchLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSearchLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSearchLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSearchLicenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSearchLicenca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblsearchLic;
    private javax.swing.JTextField textLicSearch;
    // End of variables declaration//GEN-END:variables
}
